#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>
#include <string.h>
/* run locally on 'server' called by a remote client. */
static double sum_avg;
static double median;

void swap(double *x, double *y)
{
  double t = *x;
  *x = *y;
  *y = t;
}

int piv(double *x, int s, int e)
{

  int pivot = x[e];
  int i = s - 1; 
  int j;
  for(j = s; j <= e; j++){
    if(x[j] < pivot){
      ++i;
      swap(&x[i], &x[j]);
    }
  }
  swap (&x[i+1], &x[e]);
  return i+1;
}

double *q(double *x, int s, int e)
{
  if(s < e){
    int p = piv(x, s, e);
    q(x, s, p - 1);
    q(x, p+1, e);
  }
}



/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */
double * average_1(input_data *input, CLIENT *client) 
{

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;

  u_int i;

  printf("%i\n", input->input_data.input_data_len);
  q(dp, 0, input->input_data.input_data_len - 1);
  if(input->input_data.input_data_len % 2 == 1)
  {
    median = dp[input->input_data.input_data_len / 2];
  }
  else
  {
    median = (dp[input->input_data.input_data_len/2] + dp[input->input_data.input_data_len/2 -1]) / 2;
  }
  return( &median );
}



/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
double * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }