//Here is the avg_proc file for Question 6

#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>
#include <string.h>
/* run locally on 'server' called by a remote client. */
static double sum_avg;
static double median;
static char *nums;
void swap(double *x, double *y){
  double t = *x;
  *x = *y;
  *y = t;
}

int part(double *arr, int s, int e, const int a){
  // set pivot
  int piv = arr[e];
  int i = s - 1; 
  int j;
  for(j = s; j <= e; j++){
    if(a != 0){
      if(arr[j] < piv){
        ++i;
        swap(&arr[i], &arr[j]);
      }
    }
    else{
      if(arr[j] > piv){
        ++i;
        swap(&arr[i], &arr[j]);
      }
    }
  }
  swap(&arr[i+1], &arr[e]);
  return i+1;
}

double *qs(double *arr, int s, int e, const int a){
  if(s < e){
    int p = part(arr, s, e, a);
    qs(arr, s, p - 1, a);
    qs(arr, p+1, e, a);
  }
}

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */
char **average_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;

  u_int i;
  printf("%f\n", dp[0]);

  qs(dp, 1, input->input_data.input_data_len - 1, dp[0]);
  nums = malloc(100);
  memset(nums, 0, 100);
  int ind;
  ind = 0;
  int g;
  char temp[10];
  for(g = 1; g < input->input_data.input_data_len; g++){
      snprintf(temp, 10, "%F", dp[g]);
      int len = strlen(temp);
      memcpy(&nums[ind], temp, len);
      ind += len;
      nums[ind] = ' ';
      ind+=1;
      printf("%s\n", nums);
  }
  return( &nums );
}



/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
char **average_1_svc(input_data *input, struct svc_req *svc) 
{
  CLIENT *client;
  return( average_1( input, client) );
}
